const WIDTH = 1200;
const HEIGHT = 800;
const PLAYERWIDTH = 30;
const PLAYERHEIGHT = 100;
const BALLRADIUS = 20;
const TEXTSIZE = 80;
const FPS = 200;
const SPEED = 1;
const ACCELERATION =0;
const PLAYERSPEED = 20;

module.exports = {
  WIDTH,
  HEIGHT,
  PLAYERWIDTH,
  PLAYERHEIGHT,
  BALLRADIUS,
  TEXTSIZE,
  FPS,
  SPEED,
  ACCELERATION,
  PLAYERSPEED
};
