
const FPS = 200;
const WIDTH = 1200;
const HEIGHT = 800;
const BALLRADIUS = 20;
const PLAYERWIDTH = 30;
const PLAYERHEIGHT = 100;


module.exports = {
    WIDTH:WIDTH,
    FPS:FPS,
    HEIGHT:HEIGHT,
    BALLRADIUS:BALLRADIUS,
    PLAYERHEIGHT:PLAYERHEIGHT,
    PLAYERWIDTH:PLAYERWIDTH

}